version: "3"

services:
  backend:
    build: ./backend
    environment:
      RAILS_ENV: development
    volumes:
      - ./backend:/app
      - publics:/app/public
      - tmps:/app/tmp
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    tty: true
    stdin_open: true

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  tmps:
  logs:
  publics:
